import Banner from "@/components/Banner"
import Footer from "@/components/Footer"
import LargeCard from "@/components/LargeCard"
import MediumCard from "@/components/MediumCard"
import SmallCard from "@/components/SmallCard"
import Head from "next/head"
import Header from "../components/Header"

export default function Home({ exploreData, cardData }) {
  return (
    <div>
      <Head>
        <title>Go with Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />

      <main className="mx-auto max-w-7xl px-8 sm:px-16 ">
        {/* Smallcards section */}
        <section>
          <h2 className="pb-5 pt-6 text-4xl font-semibold">Explore Nearby</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {exploreData?.map((item) => (
              <SmallCard
                key={item.img}
                image={item.img}
                distance={item.distance}
                location={item.location}
              />
            ))}
          </div>
        </section>

        {/* MediumCards section */}
        <section>
          <h2 className="py-8 text-4xl font-semibold">Live Anywhere</h2>
          <div className="-ml-3 flex space-x-3 overflow-scroll p-3 scrollbar-hide">
            {cardData?.map((item) => (
              <MediumCard key={item.img} title={item.title} img={item.img} />
            ))}
          </div>
        </section>

        {/* LargeCard secion */}

        <LargeCard
          img="https://a0.muscache.com/im/pictures/2da67c1c-0c61-4629-8798-1d4de1ac9291.jpg?im_w=1440"
          title="The Greatest Outdoors"
          description="Wishlists curated by Airbnb."
          buttonText="Get Inspired"
        />
      </main>

      <Footer/>

    </div>
  )
}

export async function getStaticProps() {
  const exploreData = await fetch("https://www.jsonkeeper.com/b/4G1G").then((res) => res.json())

  const cardData = await fetch("https://www.jsonkeeper.com/b/VHHT").then((res) => res.json())
  return {
    props: {
      exploreData,
      cardData,
    },
  }
}
